name: test-setup
on: [push]
jobs:
  run-setup:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: cd tests; $echo ${{ secrets.SUDO }} | sudo -S sh ./test-install.sh
      - run: cat /dev/null > ~/.bash_history
